jobs:
  sdk-benchmark:
    name: Benchmark SDK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.tag-version }}
    - continue-on-error: true
      id: setup-java
      name: Set up Java for build
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: 'jmhJar

          '
    - continue-on-error: true
      name: Run Benchmark
      run: 'cd sdk/trace/build

        java -jar libs/opentelemetry-sdk-trace-*-jmh.jar -rf json SpanBenchmark SpanPipelineBenchmark
        ExporterBenchmark

        '
    - continue-on-error: true
      name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        auto-push: true
        benchmark-data-dir-path: benchmarks
        gh-pages-branch: benchmarks
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file-path: sdk/trace/build/jmh-result.json
        ref: ${{ matrix.tag-version }}
        tool: jmh
    strategy:
      fail-fast: false
      matrix:
        tag-version:
        - v1.6.0
        - v1.7.0
        - v1.7.1
        - v1.10.0
        - v1.10.1
        - v1.11.0
        - v1.12.0
        - v1.13.0
        - v1.14.0
        - v1.15.0
        - v1.16.0
        - v1.17.0
        - v1.18.0
        - v1.19.0
        - v1.21.0
        - v1.22.0
        - v1.23.0
        - v1.23.1
        - v1.24.0
        - v1.25.0
        - v1.26.0
        - v1.27.0
        - v1.28.0
        - v1.29.0
        - v1.30.0
        - v1.30.1
    timeout-minutes: 10
name: Benchmark Tags
on:
  repository_dispatch:
    types: trigger-ga___benchmark-tags.yml
