jobs:
  sdk-benchmark:
    name: Benchmark SDK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: setup-java
      name: Set up Java for build
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: 'jmhJar

          '
    - continue-on-error: true
      name: Run Benchmark
      run: 'cd sdk/trace/build

        java -jar libs/opentelemetry-sdk-trace-*-jmh.jar -rf json SpanBenchmark SpanPipelineBenchmark
        ExporterBenchmark

        '
    - continue-on-error: true
      name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        auto-push: true
        benchmark-data-dir-path: benchmarks
        gh-pages-branch: benchmarks
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file-path: sdk/trace/build/jmh-result.json
        tool: jmh
    timeout-minutes: 10
name: Benchmark Main
on:
  repository_dispatch:
    types: trigger-ga___benchmark.yml
