jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Login to GitHub package registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: integration-tests/tracecontext/docker
        push: false
        tags: ghcr.io/open-telemetry/java-test-containers:w3c-tracecontext-testsuite
name: Build tracecontext testsuite
on:
  repository_dispatch:
    types: trigger-ga___build-tracecontext-testsuite.yml
