jobs:
  copy-images:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Docker login
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Copy image
      run: 'docker run --rm -v $HOME/.docker:/root/.docker gcr.io/go-containerregistry/crane:debug
        \

        cp ${{ matrix.source }} ghcr.io/open-telemetry/opentelemetry-java/${{ matrix.target_image
        }}

        '
    strategy:
      matrix:
        include:
        - source: jaegertracing/all-in-one:1.32
          target_image: jaeger:1.32
        - source: otel/opentelemetry-collector-contrib:latest
          target_image: otel-collector
        - source: shopify/toxiproxy:latest
          target_image: toxiproxy
        - source: eclipse-temurin:17-jre-focal
          target_image: openjdk17
name: Copy test container docker images (daily)
on:
  repository_dispatch:
    types: trigger-ga___docker-test-containers-daily.yml
