jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: 7
        days-before-stale: 7
        only-labels: needs author feedback
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This has been automatically marked as stale because
          it has been marked as needing author feedback and has not had any activity
          for 7 days. It will be closed if no further activity occurs within 7 days
          of this comment.

          '
        stale-pr-message: 'This has been automatically marked as stale because it
          has been marked as needing author feedback and has not had any activity
          for 7 days. It will be closed if no further activity occurs within 7 days
          of this comment.

          '
name: Issue management - run stale action
on:
  repository_dispatch:
    types: trigger-ga___issue-management-stale-action.yml
