jobs:
  issue_comment:
    if: 'contains(github.event.issue.labels.*.name, ''needs author feedback'') &&
      github.event.comment.user.login == github.event.issue.user.login

      '
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      name: Remove label
      run: 'gh issue edit --remove-label "needs author feedback" $ISSUE_NUMBER

        '
name: Issue management - remove needs feedback label
on:
  repository_dispatch:
    types: trigger-ga___issue-management-feedback-label.yml
