jobs:
  analyze:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: dependencyCheckAnalyze
    - continue-on-error: true
      if: always()
      name: Upload report
      uses: actions/upload-artifact@v4
      with:
        path: javaagent/build/reports
name: OWASP dependency check (daily)
on:
  repository_dispatch:
    types: trigger-ga___owasp-dependency-check-daily.yml
