jobs:
  misspell-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install misspell
      run: 'curl -L -o install-misspell.sh https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh

        sh ./install-misspell.sh

        '
    - continue-on-error: true
      name: Run misspell
      run: bin/misspell -error .
name: Reusable - Misspell check
on:
  repository_dispatch:
    types: trigger-ga___reusable-misspell-check.yml
