jobs:
  markdown-link-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install markdown-link-check
      run: npm install -g markdown-link-check@3.10.3
    - continue-on-error: true
      name: Run markdown-link-check
      run: "find . -type f \\\n       -name '*.md' \\\n       -not -path './CHANGELOG.md'\
        \ \\\n     | xargs .github/scripts/markdown-link-check-with-retry.sh\n"
name: Reusable - Markdown link check
on:
  repository_dispatch:
    types: trigger-ga___reusable-markdown-link-check.yml
